Layout
paulotelles/github_app_react pull request #1
Opened 2021-03-03 20:13 UTC by paulotelles

2021-03-04 14:41 UTC, vncsrbro requested changes
Dois pontos gerais:

1. É bacana separar os componentes do styled-components em um arquivo a parte, geralmente cada componente tem um /index.js para renderiza-lo e criar a lógica e um /styles.js para criar os estilos.

2. Esse é um exercício focado em React, mas não podemos esquecer do responsivo, nada muito elaborado, só trabalhar com % nos widths já ajuda deixar tudo mais fluído.

2021-03-04 14:41 UTC, vncsrbro commented on src/components/MainContent/index.js
> +export default MainContent;
A forma mais correta de se montar esse componente seria cria-lo de fato e não apenas criar o estilo dele dentro do index.js.

Você precisa receber o children (prop que referencia a um elemento filho) no componente e repassa-lo dentro do componente pai. Segue exemplo:

2021-03-04 14:41 UTC, vncsrbro commented on src/components/MainContent/index.js
> +export default MainContent;
<img width="728" alt="Captura de Tela 2021-03-04 às 11 39 15" src="https://user-images.githubusercontent.com/30932300/109980042-4492fe00-7cde-11eb-9c7d-58e08c52afd5.png">

2021-03-04 19:16 UTC, paulotelles commented on src/components/MainContent/index.js
> +export default MainContent;
Corrigido

2021-03-05 14:23 UTC, vncsrbro approved these changes

2021-03-08 17:16 UTC, merged